<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[home page is not displayed]]>
    </line>
    <line>
      <![CDATA[testinvalid1 is failed]]>
    </line>
    <line>
      <![CDATA[home page is not displayed]]>
    </line>
    <line>
      <![CDATA[testinvalidLogin is failed]]>
    </line>
    <line>
      <![CDATA[page is displayed]]>
    </line>
    <line>
      <![CDATA[Test validLogin is passed]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="82490" started-at="2019-10-30T07:10:21Z" finished-at="2019-10-30T07:11:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="82490" started-at="2019-10-30T07:10:21Z" finished-at="2019-10-30T07:11:43Z">
      <class name="com.testpom.TestLogin">
        <test-method status="PASS" signature="OpenApp()[pri:0, instance:com.testpom.TestLogin@4efbca5a]" name="OpenApp" is-config="true" duration-ms="19971" started-at="2019-10-30T12:40:21Z" finished-at="2019-10-30T12:40:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenApp -->
        <test-method status="FAIL" signature="invalid1()[pri:0, instance:com.testpom.TestLogin@4efbca5a]" name="invalid1" duration-ms="6454" started-at="2019-10-30T12:40:41Z" finished-at="2019-10-30T12:40:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.pom.EnterTimeTrack.verifyHPdisplayed(EnterTimeTrack.java:26)
	at com.testpom.TestLogin.invalid1(TestLogin.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[home page is not displayed]]>
            </line>
          </reporter-output>
        </test-method> <!-- invalid1 -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.testpom.TestLogin@4efbca5a]" name="closeApp" is-config="true" duration-ms="946" started-at="2019-10-30T12:40:47Z" finished-at="2019-10-30T12:40:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalid1 status=FAILURE method=TestLogin.invalid1()[pri:0, instance:com.testpom.TestLogin@4efbca5a] output=home page is not displayed]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[testinvalid1 is failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method status="PASS" signature="OpenApp()[pri:0, instance:com.testpom.TestLogin@4efbca5a]" name="OpenApp" is-config="true" duration-ms="19615" started-at="2019-10-30T12:40:48Z" finished-at="2019-10-30T12:41:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenApp -->
        <test-method status="FAIL" signature="invalidLogin()[pri:0, instance:com.testpom.TestLogin@4efbca5a]" name="invalidLogin" duration-ms="6001" started-at="2019-10-30T12:41:08Z" finished-at="2019-10-30T12:41:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.pom.EnterTimeTrack.verifyHPdisplayed(EnterTimeTrack.java:26)
	at com.testpom.TestLogin.invalidLogin(TestLogin.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[home page is not displayed]]>
            </line>
          </reporter-output>
        </test-method> <!-- invalidLogin -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.testpom.TestLogin@4efbca5a]" name="closeApp" is-config="true" duration-ms="985" started-at="2019-10-30T12:41:14Z" finished-at="2019-10-30T12:41:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=invalidLogin status=FAILURE method=TestLogin.invalidLogin()[pri:0, instance:com.testpom.TestLogin@4efbca5a] output=home page is not displayed]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[testinvalidLogin is failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method status="PASS" signature="OpenApp()[pri:0, instance:com.testpom.TestLogin@4efbca5a]" name="OpenApp" is-config="true" duration-ms="17362" started-at="2019-10-30T12:41:15Z" finished-at="2019-10-30T12:41:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenApp -->
        <test-method status="PASS" signature="validLogin()[pri:0, instance:com.testpom.TestLogin@4efbca5a]" name="validLogin" duration-ms="8759" started-at="2019-10-30T12:41:32Z" finished-at="2019-10-30T12:41:41Z">
          <reporter-output>
            <line>
              <![CDATA[page is displayed]]>
            </line>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:com.testpom.TestLogin@4efbca5a]" name="closeApp" is-config="true" duration-ms="2327" started-at="2019-10-30T12:41:41Z" finished-at="2019-10-30T12:41:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLogin status=SUCCESS method=TestLogin.validLogin()[pri:0, instance:com.testpom.TestLogin@4efbca5a] output=page is displayed]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test validLogin is passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.testpom.TestLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
